import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';

// Import Firebase options (generated by flutterfire configure)
// If this file doesn't exist, run: flutterfire configure
import 'firebase_options.dart';

// Import screens
import 'screens/splash/splash_screen_1.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/home/parent/parent_home_screen.dart';
import 'screens/home/therapist/therapist_home_screen.dart';
import 'screens/home/admin/admin_home_screen.dart';

// Global variable to track Firebase initialization status
bool firebaseInitialized = false;
String? firebaseError;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    firebaseInitialized = true;
    debugPrint('✓ Firebase initialized successfully');
  } catch (e) {
    firebaseInitialized = false;
    firebaseError = e.toString();
    debugPrint('✗ Firebase initialization error: $e');
    debugPrint('');
    debugPrint('════════════════════════════════════════════════════════════════');
    debugPrint('⚠️  FIREBASE NOT CONNECTED');
    debugPrint('════════════════════════════════════════════════════════════════');
    debugPrint('');
    debugPrint('To fix this:');
    debugPrint('1. Go to https://console.firebase.google.com/');
    debugPrint('2. Select your project: thera1-app');
    debugPrint('3. Enable these services:');
    debugPrint('   - Authentication (Email/Password)');
    debugPrint('   - Firestore Database');
    debugPrint('4. Wait 2-3 minutes after enabling');
    debugPrint('5. Restart this app');
    debugPrint('');
    debugPrint('════════════════════════════════════════════════════════════════');
    debugPrint('');
  }

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key}); // REQUIRED FOR TESTING

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Thera1',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
        // App-wide color scheme
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF4A90E2),
          primary: const Color(0xFF4A90E2),
          secondary: const Color(0xFF6BA3E8),
        ),
      ),
      home: const SplashScreen1(),
      routes: {
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/parent-home': (context) => const ParentHomeScreen(),
        '/therapist-home': (context) => const TherapistHomeScreen(),
        '/admin-home': (context) => const AdminHomeScreen(),
      },
    );
  }
}
